name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - uses: actions/setup-node@v2
    - name: curl moz_central
      run: curl https://hg.mozilla.org/mozilla-central/archive/tip.zip/js/src/jit-test/tests/ --output moz-central.zip
    - name: unzip moz-central
      run: unzip -qq moz-central.zip -d moz-central
    - name: Run tests
      run: cargo test --features=moz_central
      env:
        RUST_MIN_STACK: 99999999
    - name: Check syntax
      run: cargo fmt --all -- --check
